############################################################
#
# cas服务
# web访问端口号  约定：9092
#
############################################################
server:
  port: 9092
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可


spring:
  redis:
    database: 10
    host: 121.4.149.240
    port: 6379
    password: redis123